### ISSUE TITLE
A few policy questions

### ISSUE THREAD

**Issue by gabesullice** [icecave/parity#15]
Hi there!

The Drupal project is considering adding a library that will add this library as one of our dev dependencies and so we're performing a standard stability review :)

I'm curious if you have any official policies documented somewhere WRT to:

- Security releases
  - For example, does more than one version receive security fixes, or only the current version?
- Release windows/cadence
  - For example, do they happen as necessary on any given day, or on a set schedule after a certain passage of time (e.g. once a month)?
- Backwards compatibility guarantees
  - I see the project uses semver, so I assume the major version promises not to break BC. However, is there any guarantee that a version will be supported for some period of time (an LTS version, for example)?

PS. I totally understand that these questions might be a little over the top if this project is a one-person shop, for the most part ;) Due diligence and whatnot.

**Comment by wimleers** [comment]
Related: is the 1.x branch still actively maintained? (Does it get security releases?)

The library in question is https://github.com/justinrainbow/json-schema, and it uses `icecave/parity` version 1.0.0, which was released in 2014 (>4 years ago). It seems unlikely that there would be a need for another release, but if there is, would you do so?

**Comment by jmalloc** [comment]
Hi,

This is definitely a one person shop nowadays. For a little background, most of the packages under the IcecaveStudios organisation were created by myself and some of my colleagues for production use  at our day job. Many of them are still used, but we are moving away from PHP, generally, and so they do not see active development. This package and the `repr` package (see IcecaveStudios/repr#4) are both currently used in production.

I don't have any official policies documented, but to address your questions specifically, the workflow is:

1. Fixes are generally only made to the master branch, and published as a new semver tag.  On occasion I have applied fixes to a previous major version, if necessary.

2. There is no set window. Releases are made as necessary. Typically I will tag disruptive changes as a pre-release version before creating a stable semver tag.

3. Semver is adhered to somewhat religiously. I also try to limit the velocity of new major versions to avoid unnecessary version shuffling, but there is no set window for major version support.

In regards to maintenance releases against v1.  I am happy to apply changes to this version if necessary, however it's worth pointing out that the main reason a new major semver tag was released is because support for PHP 5.0 was dropped.  My preference is to support only PHP versions that still receive security fixes, as per http://php.net/supported-versions.php.

One final point. I have been trying to cull the truly unmaintained libraries from this organisation, and intend to move those that remain to the [recoilphp](http://github.com/recoilphp) organisation, which I do actively maintain. When that time comes I will need to rename these packages in the least disruptive way possible, which would have to include leaving existing versions of this library in place at this location.  Obviously, this is more an issue for the maintainers of the `json-schema` package, but I just thought I'd mention it.

Please take these answers as applicable to IcecaveStudios/repr#4 as well :)

**Comment by xjm** [comment]
Thanks @jmalloc for the quick response; that's definitely helpful!

**Comment by xjm** [comment]
One followup question -- do you have any process or recommendation for people to report any security issues that might come up to you privately? And would you aim for coordinated disclosure if something did affect the package?
